import AssemblyP1.Model
import AssemblyP1.OpenProblem
import AssemblyP1.SourceFaithfulIs
import AssemblyP1.ExactVariantECounterexample
import AssemblyP1.FixedLengthExactCounterexample
import AssemblyP1.FixedLengthBinomialCounterexample
import AssemblyP1.Section62BridgingCounterexample
import AssemblyP1.SameLengthSection62Counterexample
import AssemblyP1.Section62BidirectedFlow
import AssemblyP1.FiniteSamplingCounterexample
import AssemblyP1.PopulationReduction
import AssemblyP1.OrientedRigidity
import AssemblyP1.RepeatAdapter
import AssemblyP1.OrientedFinalRigidity
import AssemblyP1.BridgingBridge
import AssemblyP1.OrientedSameLengthML
import AssemblyP1.SameLengthExactMLCounterexample
import AssemblyP1.SameLength62Maximizer
import AssemblyP1.WraparoundTripleRepeat
import AssemblyP1.MLEscape
import AssemblyP1.PopulationUniqueness
import AssemblyP1.AAABConverse

/-! ## Axiom audit for the #88 deliverable (issue #88) -/

#print axioms AssemblyP1.SameLengthExactMLCounterexample.same_length_exact_ML_refutation_62
#print axioms AssemblyP1.SameLengthExactMLCounterexample.competitor_spelledFeasible62
#print axioms AssemblyP1.SameLengthExactMLCounterexample.section62_maxLikelihood_refuted
#print axioms AssemblyP1.SameLengthExactMLCounterexample.truth_information_feasible
#print axioms AssemblyP1.SameLengthExactMLCounterexample.truth_no_long_triple_repeat
#print axioms AssemblyP1.BridgingBridge.bridgingLength
#print axioms AssemblyP1.BridgingBridge.informationFeasible_tripleRepeat_ge_G_sub_L
#print axioms AssemblyP1.BridgingBridge.informationFeasible_sharp_no_long_triple_repeat
#print axioms AssemblyP1.OrientedSameLengthML.informationFeasible_exactLik_maximizer
#print axioms AssemblyP1.OrientedSameLengthML.covering_constant_reads_is_constant
#print axioms AssemblyP1.OrientedSameLengthML.truth_is_spelled_candidate_of_realization
#print axioms AssemblyP1.SameLength62Maximizer.informationFeasible_62_maximizer
#print axioms AssemblyP1.SameLength62Maximizer.genuine62_is_spelled_candidate
#print axioms AssemblyP1.SameLength62Maximizer.genuine62_support_eq
#print axioms AssemblyP1.SameLength62Maximizer.genuine62_molecule_eq
#print axioms AssemblyP1.SameLength62Maximizer.visited_of_positive_throughput
#print axioms AssemblyP1.SameLength62Maximizer.oriented_support_eq_of_genuine62
#print axioms AssemblyP1.WraparoundTripleRepeat.informationFeasible_does_not_exclude_long_triple_repeat
#print axioms AssemblyP1.WraparoundTripleRepeat.wraparound_information_feasible
#print axioms AssemblyP1.WraparoundTripleRepeat.wraparound_has_long_triple_repeat

/-! ## Axiom audit for the wraparound-regime result of #88
(`AssemblyP1.MLEscape`) -/

#print axioms AssemblyP1.MLEscape.Is62SpelledMLMax
#print axioms AssemblyP1.MLEscape.informationFeasible_62_spelledML_of_no_long_triple
#print axioms AssemblyP1.MLEscape.HasMidRangeTripleRepeat.longTriple
#print axioms AssemblyP1.MLEscape.informationFeasible_no_midRangeTriple
#print axioms AssemblyP1.MLEscape.longTripleFree_no_midRangeTriple
#print axioms AssemblyP1.MLEscape.exactLik_le_of_spec_le
#print axioms AssemblyP1.MLEscape.observed_spectral_excess_of_ml_failure
#print axioms AssemblyP1.MLEscape.candidate_is_massG_positive_circulation
#print axioms AssemblyP1.MLEscape.eq_specCount_of_massG_le
#print axioms AssemblyP1.MLEscape.ml_failure_gives_spectral_escape
#print axioms AssemblyP1.MLEscape.informationFeasible_62_spelledML_of_escape_crux
#print axioms AssemblyP1.MLEscape.culprit_instance_checked
#print axioms AssemblyP1.MLEscape.cand0_is_escape
#print axioms AssemblyP1.MLEscape.truth0_has_midrange_triple
