import AssemblyP1.SameLength62TieUniqueness
import AssemblyP1.SameLength62Nonprimitive

open AssemblyP1.SameLength62TieUniqueness
open AssemblyP1.SameLength62Nonprimitive

#print axioms AssemblyP1.SameLength62TieUniqueness.Is_spectrum_eq_of_support_eq
#print axioms AssemblyP1.SameLength62TieUniqueness.support_eq_iff_specCount_eq
#print axioms AssemblyP1.SameLength62TieUniqueness.informationFeasible_62_exact_tie
#print axioms AssemblyP1.SameLength62TieUniqueness.same_support_word_ties_truth
#print axioms AssemblyP1.SameLength62TieUniqueness.maximizer_and_tie_of_Is_and_62
#print axioms AssemblyP1.SameLength62TieUniqueness.support_rigidity_iff_fibre_singleton
#print axioms AssemblyP1.SameLength62TieUniqueness.unique_62_maximizer_up_to_rotation_of_support_rigidity
#print axioms AssemblyP1.SameLength62TieUniqueness.no_interleaved_long_repeats_of_Is
#print axioms AssemblyP1.SameLength62TieUniqueness.unique_maximizer_up_to_rotation_of_residue
#print axioms AssemblyP1.SameLength62TieUniqueness.truth6_not_information_feasible
#print axioms AssemblyP1.SameLength62TieUniqueness.spectra_eq_G6_L2
#print axioms AssemblyP1.SameLength62TieUniqueness.support_eq_G6_L2
#print axioms AssemblyP1.SameLength62TieUniqueness.cand6_not_cyclic_shift_of_truth6
#print axioms AssemblyP1.SameLength62TieUniqueness.bbt_premise_refuted_G6_L2
#print axioms AssemblyP1.SameLength62TieUniqueness.equal_spectrum_not_cyclic_shift
#print axioms AssemblyP1.SameLength62TieUniqueness.truth4_information_feasible
#print axioms AssemblyP1.SameLength62TieUniqueness.truth4_represents62
#print axioms AssemblyP1.SameLength62TieUniqueness.truth4_spelledFeasible62
#print axioms AssemblyP1.SameLength62TieUniqueness.truth4_is62Candidate
#print axioms AssemblyP1.SameLength62TieUniqueness.isCyclicShift_iff_fin_shift
#print axioms AssemblyP1.SameLength62TieUniqueness.truth4_support_rigid
#print axioms AssemblyP1.SameLength62TieUniqueness.truth4_tie_instance
#print axioms AssemblyP1.SameLength62TieUniqueness.informationFeasible_P2
#print axioms AssemblyP1.SameLength62TieUniqueness.informationFeasible_Ukkonen
#print axioms AssemblyP1.SameLength62TieUniqueness.rotEquiv_iff_isCyclicShift
#print axioms AssemblyP1.SameLength62TieUniqueness.fibre_singleton_of_Iss_and_obstruction
#print axioms AssemblyP1.SameLength62TieUniqueness.alt4_information_feasible
#print axioms AssemblyP1.SameLength62TieUniqueness.alt4_not_P1
#print axioms AssemblyP1.SameLength62TieUniqueness.iss_does_not_imply_P1
#print axioms AssemblyP1.SameLength62TieUniqueness.bbTP2Prim_of_94
#print axioms AssemblyP1.SameLength62TieUniqueness.unique_62_maximizer_up_to_rotation_of_primitive

#print axioms AssemblyP1.MLEscape.informationFeasible_62_spelledML
#print axioms AssemblyP1.MLEscape.informationFeasible_62_spelledML_of_exact_subset
#print axioms AssemblyP1.SameLength62Maximizer.informationFeasible_62_maximizer

#print axioms AssemblyP1.SameLength62Nonprimitive.np6_information_feasible
#print axioms AssemblyP1.SameLength62Nonprimitive.np6_nonprimitive
#print axioms AssemblyP1.SameLength62Nonprimitive.np6_P2
#print axioms AssemblyP1.SameLength62Nonprimitive.np6_not_square
#print axioms AssemblyP1.SameLength62Nonprimitive.p2_does_not_force_k2
