import AssemblyP1.HistoricalCoverageSameLengthWitnesses

open AssemblyP1.HistoricalCoverageSameLength

#print axioms AssemblyP1.HistoricalCoverageSameLength.denseSampledStarts_historicalCovers
#print axioms AssemblyP1.HistoricalCoverageSameLength.regA_historicalCovers
#print axioms AssemblyP1.HistoricalCoverageSameLength.regA_not_covers
#print axioms AssemblyP1.HistoricalCoverageSameLength.regB_covers
#print axioms AssemblyP1.HistoricalCoverageSameLength.regB_not_historicalCovers
#print axioms AssemblyP1.HistoricalCoverageSameLength.W1.historicalCovers
#print axioms AssemblyP1.HistoricalCoverageSameLength.W1.matchStarts_eq
#print axioms AssemblyP1.HistoricalCoverageSameLength.W1.w1_historical_information_feasible
#print axioms AssemblyP1.HistoricalCoverageSameLength.W1.w1_historical_full_se62_flow_counterexample
#print axioms AssemblyP1.HistoricalCoverageSameLength.W1.w1_historical_maximality_refuted
#print axioms AssemblyP1.HistoricalCoverageSameLength.W2.historicalCovers
#print axioms AssemblyP1.HistoricalCoverageSameLength.W2.matchStarts_eq
#print axioms AssemblyP1.HistoricalCoverageSameLength.W2.w2_historical_information_feasible
#print axioms AssemblyP1.HistoricalCoverageSameLength.W2.w2_historical_full_se62_flow_counterexample
#print axioms AssemblyP1.HistoricalCoverageSameLength.W2.w2_historical_maximality_refuted
