#!/usr/bin/env python3
"""Bounded exact §6.2 search: a bridging truth whose feasible flow is beaten by
a strictly better arbitrary feasible flow.

Object (Medvedev-Brudno 2009, PMC3154397, §3.1-3.4, §5.2, §6.1-6.2)
=====================================================================

* Vertices are the observed read *molecules* (unordered reverse-complement
  pairs); ports 0/1 are the two 5' ends.  A bidirected overlap edge X.p -> Y.q
  exists with length l = the maximal suffix/prefix match of the exit strand of
  X and the entry strand of Y; only 1 <= l <= L-1 (proper) is considered.
* The graph is transitively reduced as MB09 names it (Myers 2005): an overlap
  of length l is removed when it is spelled by a two-step path X -> Z -> Y
  whose two overlaps satisfy l1,l2 > l and l = l1 + l2 - L.
* Every read vertex has lower bound 1 and upper bound infinity; a flow is a
  collection of walks; a closed flow decomposes into a nonnegative integer
  combination of elementary directed port circuits.
* The §6.1 objective is the product of per-type binomials with external true
  genome length N:  prod_w (d_w/N)^{x_w} (1 - d_w/N)^{n-x_w}.

Relation to scripts/independent_se62_bidirected_model.py
========================================================

That script's ``transitive_reduction`` tests ``e1.length < e.length and
e2.length < e.length``, i.e. it keeps only reductions by *shorter* overlaps.
That is the reverse of the Myers reading the source names, so at ``o_min = 1``
it removes (almost) nothing and its flow cone is strictly too large: for the
``AAATT`` reads it admits ``d_AAT != d_TAA`` (e.g. ``(2,2,1)``), whereas the
correct Myers reduction leaves only the two length-1 edges
``AAT.p1 -> TAA.p0`` / ``TAA.p0 -> AAT.p1`` and forces ``d_AAT = d_TAA``.  The
reduction here is reconstructed from the source definition, not inherited; it
agrees with the independent rule audit of
``scripts/verify_se62_edge_and_reduction_rules.py`` and the note
``docs/section62-edge-and-transitive-reduction-rules.md``.  The bug does not
affect that model's ``o_min = 2`` search (no length-1 edges exist there).

What is searched
================

For a truth S (circular binary string), read multiset (start positions), and
read length L with strict Shomorony-Krause-Courtade-Tse bridging I_s:

  * the observed support must equal the full window spectrum of S, so the
    truth's cyclic window circuit is a closed §6.2 flow d_S on the read graph;
  * enumerate every closed §6.2 flow throughput vector reachable in the stated
    box (coordinates in [1, N], the only binding bound), and report when the
    §6.1 likelihood optimum is strictly above ``L(d_S)``;
  * record whether that optimum is itself *spellable* by a single circular
    molecule, i.e. whether it is a sequence spectrum or only a flow.

Completeness limits (explicit)
==============================

* Finite box: alphabet {A,T}; L = 3; G = |S| in {4,5,6,7}; N = G;
  o_min in {1,2}; read multiset size n in {2,3,4}; all start multisets of that
  size; every circular truth up to rotation.
* Flows: the circuit monoid is generated by elementary circuits of length
  <= MAXCIRC; throughput vectors are enumerated with coordinates in [1, N]
  (a vector's total visits is at most n_molecules * N, so no extra sum bound
  is imposed).  This is exhaustive inside those coordinate bounds.
* Spellability: single circular molecules enumerated with length <= N + 2 and
  whose every L-window is an observed read type.
* Nothing outside these boxes is claimed.  This is EVIDENCE, not proof.

Exits non-zero on any failed assertion.
"""

from collections import defaultdict
from fractions import Fraction
from itertools import combinations, combinations_with_replacement, product

A, T = 0, 1
L = 3

MAXCIRC = 16


# ---------------------------------------------------------------------------
# strings, molecules, circular windows
# ---------------------------------------------------------------------------

def revcomp(w):
    return tuple(1 - b for b in reversed(w))


def mol_class(w):
    return min(w, revcomp(w))


def circ(seq, start, length):
    g = len(seq)
    return tuple(seq[(start + i) % g] for i in range(length))


def word(w):
    return "".join("T" if b else "A" for b in w)


def strand_entry(molecule, q):
    """Strand traversed when the molecule is entered at port q."""
    return molecule if q == 0 else revcomp(molecule)


def full_spectrum(seq, read_len):
    counts = defaultdict(int)
    for s in range(len(seq)):
        counts[mol_class(circ(seq, s, read_len))] += 1
    return counts


def observed_spectrum(seq, starts, read_len):
    counts = defaultdict(int)
    for s in starts:
        counts[mol_class(circ(seq, s, read_len))] += 1
    return counts


# ---------------------------------------------------------------------------
# §6.2 bidirected overlap graph in port form
# ---------------------------------------------------------------------------

def overlap_edges(molecules, read_len, o_min):
    """All maximal proper bidirected overlaps of length >= o_min.

    An edge is (X, p, Y, q, l): leave molecule index X through exit port p (so
    the traversed strand is strand_entry(X, 1-p)) and enter molecule Y at port
    q (traversed strand strand_entry(Y, q)); l is the maximal match.
    """
    edges = set()
    n = len(molecules)
    for Xi in range(n):
        for Yi in range(n):
            for p in (0, 1):
                exit_strand = strand_entry(molecules[Xi], 1 - p)
                for q in (0, 1):
                    entry_strand = strand_entry(molecules[Yi], q)
                    best = 0
                    for l in range(1, read_len):
                        if exit_strand[read_len - l:] == entry_strand[:l]:
                            best = l
                    if best >= o_min:
                        edges.add((Xi, p, Yi, q, best))
    return edges


def myers_reduce(edges, n_molecules, read_len):
    """Remove overlaps implied by a two-step path of strictly longer overlaps.

    Edge e = (X,p,Y,q,l) is removed iff there is a molecule Z and a port q1
    with (X,p,Z,q1,l1), (Z,1-q1,Y,q,l2) in the graph, l1,l2 > l and
    l1 + l2 - L = l.  (Myers 2005; MB09 §6.2 names this procedure.)
    """
    kept, removed = [], []
    for e in sorted(edges, key=lambda z: z[4]):
        Xi, p, Yi, q, l = e
        reducible = False
        for Zi in range(n_molecules):
            for q1 in (0, 1):
                for f in edges:
                    if f[0] != Xi or f[1] != p or f[2] != Zi or f[3] != q1:
                        continue
                    for h in edges:
                        if (h[0] == Zi and h[1] == 1 - q1
                                and h[2] == Yi and h[3] == q
                                and f[4] > l and h[4] > l
                                and f[4] + h[4] - read_len == l):
                            reducible = True
                if reducible:
                    break
            if reducible:
                break
        (removed if reducible else kept).append(e)
    return kept, removed


def elementary_circuits(reduced_edges, n_molecules, max_circ=MAXCIRC):
    """Elementary directed port circuits, as (throughput_vector, edge_mults).

    State is (molecule, exit_port).  Traversing X.p -> Y.q enters Y at q and so
    leaves Y through port 1-q; the successor state is (Y, 1-q).  Each traversal
    visits its target molecule Y, so the throughput vector counts targets.
    """
    adj = defaultdict(list)
    for ei, (Xi, p, Yi, q, l) in enumerate(reduced_edges):
        adj[(Xi, p)].append(((Yi, 1 - q), Yi, ei))
    states = sorted(adj)
    idx = {s: i for i, s in enumerate(states)}
    seen = set()
    circuits = []

    def dfs(start, cur, visited, trace):
        for (nxt, Y, ei) in adj[cur]:
            if nxt == start:
                full = tuple(trace + [(cur, Y, ei)])
                # canonical rotation: start at the minimal state index
                if min(idx[c] for c, _, _ in full) != idx[start]:
                    continue
                sig = tuple((idx[c], Y) for c, Y, _ in full)
                if sig in seen:
                    continue
                seen.add(sig)
                throughput = [0] * n_molecules
                edge_mults = [0] * len(reduced_edges)
                for _, Z, e2 in full:
                    throughput[Z] += 1
                    edge_mults[e2] += 1
                circuits.append((tuple(throughput), tuple(edge_mults)))
            elif nxt not in visited and len(trace) + 1 < max_circ:
                dfs(start, nxt, visited + [nxt],
                    trace + [(cur, Y, ei)])

    for start in states:
        dfs(start, start, [start], [])
    return circuits


def reachable_throughputs(generators, n_molecules, N, sum_cap):
    """All throughput vectors x + sum of generators with coords in [0,N]."""
    reach = set()
    stack = [tuple([0] * n_molecules)]
    while stack:
        v = stack.pop()
        if v in reach:
            continue
        reach.add(v)
        for g in generators:
            w = tuple(a + b for a, b in zip(v, g))
            if sum(w) <= sum_cap and all(c <= N for c in w) and w not in reach:
                stack.append(w)
    return reach


def spellable_throughputs(molecules_set, read_len, max_len):
    """Spectra of single circular molecules (length <= max_len) all of whose
    L-windows are observed read types."""
    out = {}
    for Gd in range(read_len, max_len + 1):
        for bits in product((A, T), repeat=Gd):
            spec = full_spectrum(bits, read_len)
            if set(spec) <= molecules_set:
                key = tuple(sorted(spec.items()))
                out.setdefault(key, spec)
    return out


# ---------------------------------------------------------------------------
# strict Shomorony et al. Eq. (1) bridging predicate
# ---------------------------------------------------------------------------

def _maximal_repeat_pairs(seq, ell):
    g = len(seq)
    out = []
    for t1, t2 in combinations(range(g), 2):
        if circ(seq, t1, ell) != circ(seq, t2, ell):
            continue
        if seq[(t1 - 1) % g] == seq[(t2 - 1) % g]:
            continue
        if seq[(t1 + ell) % g] == seq[(t2 + ell) % g]:
            continue
        out.append((t1, t2))
    return out


def _maximal_triple_repeats(seq, ell):
    g = len(seq)
    out = []
    for t1, t2, t3 in combinations(range(g), 3):
        if not (circ(seq, t1, ell) == circ(seq, t2, ell) == circ(seq, t3, ell)):
            continue
        pre = {seq[(t - 1) % g] for t in (t1, t2, t3)}
        post = {seq[(t + ell) % g] for t in (t1, t2, t3)}
        if len(pre) == 1 or len(post) == 1:
            continue
        out.append((t1, t2, t3))
    return out


def _bridges_copy(seq, starts, read_len, t, ell):
    """Some read strictly contains copy [t, t+ell) on a common lift."""
    g = len(seq)
    for r in starts:
        for k in (-2, -1, 0, 1, 2):
            rr = r + k * g
            if rr < t and t + ell < rr + read_len:
                return True
    return False


def _cyclically_interleaved(a, b, c, d, g):
    if len({a % g, b % g, c % g, d % g}) < 4:
        return False

    def between(x, lo, hi):
        return 0 < (x - lo) % g < (hi - lo) % g

    return ((between(c, a, b) and between(d, b, a))
            or (between(d, a, b) and between(c, b, a)))


def check_I_s(seq, starts, read_len):
    """Strict I_s: coverage, every maximal triple repeat all-bridged, every
    interleaved maximal repeat pair bridged.  Returns failing witnesses."""
    g = len(seq)
    failures = []
    covered = set()
    for r in starts:
        for i in range(read_len):
            covered.add((r + i) % g)
    if covered != set(range(g)):
        failures.append(("coverage", sorted(set(range(g)) - covered)))

    for ell in range(1, g + 1):
        for triple in _maximal_triple_repeats(seq, ell):
            for t in triple:
                if not _bridges_copy(seq, starts, read_len, t, ell):
                    failures.append(("triple", ell, t))

    for ell1 in range(1, g + 1):
        pairs1 = _maximal_repeat_pairs(seq, ell1)
        for ell2 in range(1, g + 1):
            pairs2 = _maximal_repeat_pairs(seq, ell2)
            for (a, b) in pairs1:
                for (c, d) in pairs2:
                    if (a, b, c, d) == (c, d, a, b):
                        continue
                    if not _cyclically_interleaved(a, b, c, d, g):
                        continue
                    if not any(_bridges_copy(seq, starts, read_len, t, ell)
                               for (t, ell) in ((a, ell1), (b, ell1),
                                                (c, ell2), (d, ell2))):
                        failures.append(("interleaved", ell1, a, b, ell2, c, d))
    return failures


# ---------------------------------------------------------------------------
# §6.1 separable binomial objective
# ---------------------------------------------------------------------------

def likelihood(x, d, N):
    n = sum(x.values())
    out = Fraction(1)
    for w, xw in x.items():
        dw = d.get(w, 0)
        if not (0 <= dw <= N):
            return Fraction(0)
        out *= Fraction(dw, N) ** xw * Fraction(N - dw, N) ** (n - xw)
    return out


# ---------------------------------------------------------------------------
# circulation certificate for a target throughput
# ---------------------------------------------------------------------------

def realize_throughput(target, circuits, n_molecules, N, max_terms=12):
    """Express target as a sum of elementary-circuit throughput vectors.

    Returns an explicit edge-multiplicity circulation, or None.  Exact BFS over
    integer combinations, bounded by max_terms and the coordinate caps.
    """
    target = tuple(target)
    if all(c == 0 for c in target):
        return tuple([0] * len(circuits[0][1])) if circuits else None
    # BFS over vectors, remembering one witness combination and edge mults
    from collections import deque
    zero = tuple([0] * n_molecules)
    prev = {zero: None}
    q = deque([zero])
    while q:
        v = q.popleft()
        for ci, (gvec, gedge) in enumerate(circuits):
            w = tuple(a + b for a, b in zip(v, gvec))
            if any(c > N for c in w) or w in prev:
                continue
            prev[w] = (v, ci)
            if w == target:
                # reconstruct
                edge_mults = [0] * len(gedge)
                cur = w
                while prev[cur] is not None:
                    pv, pci = prev[cur]
                    for j, val in enumerate(circuits[pci][1]):
                        edge_mults[j] += val
                    cur = pv
                return tuple(edge_mults)
            q.append(w)
    return None


def verify_circulation(edge_mults, reduced_edges, n_molecules):
    """Check port balance and return the throughput vector of an edge flow."""
    balance = defaultdict(int)
    throughput = [0] * n_molecules
    for ei, mult in enumerate(edge_mults):
        Xi, p, Yi, q, l = reduced_edges[ei]
        balance[(Xi, p)] -= mult        # leaving X at port p
        balance[(Yi, 1 - q)] += mult    # entering Y at q, exiting at 1-q
        throughput[Yi] += mult
    assert all(b == 0 for b in balance.values()), sorted(balance.items())
    return tuple(throughput)


# ---------------------------------------------------------------------------
# the witness and the bounded search
# ---------------------------------------------------------------------------

def witness():
    S = [A, A, A, T, T]                 # AAATT, G = 5
    starts = [0, 0, 1, 4]               # repeated read at 0
    N = len(S)
    x = observed_spectrum(S, starts, L)
    dS = full_spectrum(S, L)
    return S, starts, x, dS, N


def certificate(S, starts, N=None, o_min=1):
    G = len(S)
    if N is None:
        N = G
    x = observed_spectrum(S, starts, L)
    dS = full_spectrum(S, L)
    n = sum(x.values())

    fails = check_I_s(S, starts, L)
    assert not fails, f"I_s failed: {fails}"
    assert set(x) == set(dS), "observed support != full window support"

    molecules = sorted(set(dS))
    ids = {m: i for i, m in enumerate(molecules)}
    raw = overlap_edges(molecules, L, o_min)
    reduced, removed = myers_reduce(raw, len(molecules), L)

    # truth is a feasible closed flow with throughput dS
    circuits = elementary_circuits(reduced, len(molecules))
    dS_vec = tuple(dS[m] for m in molecules)
    circ_dS = realize_throughput(dS_vec, circuits, len(molecules), N)
    assert circ_dS is not None, "truth throughput not realizable"
    assert verify_circulation(circ_dS, reduced, len(molecules)) == dS_vec, \
        "truth circulation does not realize d_S"

    # enumerate the §6.2 flow cone in the box and find the §6.1 optimum
    generators = [v for v, _ in circuits]
    reach = reachable_throughputs(generators, len(molecules), N,
                                  len(molecules) * N)
    feasible = [v for v in reach
                if all(1 <= c <= N for c in v)]
    best = max(feasible, key=lambda v: likelihood(
        x, {molecules[i]: v[i] for i in range(len(molecules))}, N))
    best_d = {molecules[i]: best[i] for i in range(len(molecules))}
    ratio = likelihood(x, best_d, N) / likelihood(x, dS, N)

    # spellability of the optimal throughput
    spelled = spellable_throughputs(set(molecules), L, N + 2)
    best_key = tuple(sorted(best_d.items()))
    best_spellable = best_key in spelled

    return {
        "S": tuple(S), "starts": tuple(starts), "o_min": o_min, "N": N,
        "x": x, "dS": dS, "molecules": molecules, "ids": ids,
        "raw": raw, "reduced": reduced, "removed": removed,
        "circuits": circuits, "circ_dS": circ_dS,
        "best": best, "best_d": best_d, "best_spellable": best_spellable,
        "ratio": ratio, "spelled": spelled, "reachable": reach,
    }


def bounded_search(G_values=(4, 5, 6, 7), n_values=(2, 3, 4),
                   o_min_values=(1, 2)):
    """Exhaustive inside the stated box; returns list of hit records."""
    hits = []
    for G in G_values:
        N = G
        for bits in product((A, T), repeat=G):
            S = list(bits)
            if min(tuple(S[i:] + S[:i]) for i in range(G)) != tuple(S):
                continue
            for n in n_values:
                if n > G:
                    continue
                for starts in combinations_with_replacement(range(G), n):
                    if check_I_s(S, starts, L):
                        continue
                    x = observed_spectrum(S, starts, L)
                    dS = full_spectrum(S, L)
                    if set(x) != set(dS):
                        continue
                    molecules = sorted(set(dS))
                    for o_min in o_min_values:
                        raw = overlap_edges(molecules, L, o_min)
                        if not raw:
                            continue
                        reduced, _ = myers_reduce(raw, len(molecules), L)
                        circuits = elementary_circuits(reduced, len(molecules))
                        if not circuits:
                            continue
                        gens = [v for v, _ in circuits]
                        reach = reachable_throughputs(gens, len(molecules),
                                                      N, len(molecules) * N)
                        feas = [v for v in reach if all(1 <= c <= N for c in v)]
                        dS_vec = tuple(dS[m] for m in molecules)
                        if dS_vec not in feas:
                            continue
                        best = max(feas, key=lambda v: likelihood(
                            x, {molecules[i]: v[i]
                                for i in range(len(molecules))}, N))
                        r = (likelihood(x, {molecules[i]: best[i]
                                            for i in range(len(molecules))}, N)
                             / likelihood(x, dS, N))
                        if r > 1:
                            spelled = spellable_throughputs(
                                set(molecules), L, N + 2)
                            bk = tuple(sorted(
                                (molecules[i], best[i])
                                for i in range(len(molecules))))
                            hits.append({
                                "S": tuple(S), "starts": tuple(starts),
                                "o_min": o_min, "molecules": molecules,
                                "dS": dS_vec, "best": best, "ratio": r,
                                "best_spellable": bk in spelled,
                                "x": x,
                            })
    return hits


def main():
    print("§6.2 bridging truth vs strictly better arbitrary feasible flow")
    print("=" * 68)

    # ---- repair check: Myers reduction is not the reversed one -------------
    S = [A, A, A, T, T]
    starts = [0, 0, 1, 4]
    x = observed_spectrum(S, starts, L)
    dS = full_spectrum(S, L)
    molecules = sorted(set(dS))
    raw1 = overlap_edges(molecules, L, 1)
    reduced1, removed1 = myers_reduce(raw1, len(molecules), L)
    by_len = defaultdict(int)
    for e in reduced1:
        by_len[e[4]] += 1
    print(f"AAATT reduced graph (o_min=1): raw={len(raw1)} "
          f"kept={len(reduced1)} removed={len(removed1)} by_len={dict(by_len)}")
    assert by_len[1] == 2, by_len              # exactly two length-1 edges
    assert by_len[2] == 10, by_len             # ten length-2 edges
    surviving = sorted(e for e in reduced1 if e[4] == 1)
    print(f"  surviving length-1 edges: {surviving}")

    # ---- the witness -------------------------------------------------------
    S, starts, x, dS, N = witness()
    cert = certificate(S, starts, N, o_min=1)
    n = sum(x.values())
    print()
    print("Witness")
    print("-" * 68)
    print(f"  truth S = {word(S)}  G={len(S)} L={L} N={N} o_min=1")
    print(f"  read starts {list(starts)}  (repeated start 0)")
    print(f"  observed x = { {word(k): v for k, v in sorted(x.items())} }  n={n}")
    print(f"  truth flow d_S = "
          f"{ {word(k): v for k, v in sorted(dS.items())} }")
    print(f"  truth circulation edge mults = {cert['circ_dS']}")

    best_d = cert["best_d"]
    print(f"  ML flow d* = { {word(k): v for k, v in sorted(best_d.items())} }")
    # explicit circulation for d*
    circ_best = realize_throughput(cert["best"], cert["circuits"],
                                   len(cert["molecules"]), N)
    assert circ_best is not None
    tp = verify_circulation(circ_best, cert["reduced"], len(cert["molecules"]))
    assert tp == cert["best"], (tp, cert["best"])
    print(f"  ML circulation edge mults = {circ_best}")
    print(f"  ML throughput is spellable by a single molecule: "
          f"{cert['best_spellable']}")
    print(f"  L_{6.1}(d*)/L_{6.1}(d_S) = {cert['ratio']} = "
          f"{float(cert['ratio']):.6f} > 1")
    assert cert["ratio"] > 1
    assert not cert["best_spellable"], "expected a non-spellable optimum here"

    # independent re-derivation of the ratio by hand
    def factor(w, dw):
        return Fraction(dw, N) ** x[w] * Fraction(N - dw, N) ** (n - x[w])
    manual = (factor(mol_class((A, A, A)), 3)
              * factor(mol_class((A, A, T)), 1)
              * factor(mol_class((T, A, A)), 1))
    manual /= (factor(mol_class((A, A, A)), 1)
               * factor(mol_class((A, A, T)), 2)
               * factor(mol_class((T, A, A)), 2))
    assert manual == cert["ratio"], (manual, cert["ratio"])
    print(f"  manual ratio check: {manual} == {cert['ratio']}")

    # dS is feasible but is NOT the ML optimum; d* non-spellable
    assert cert["dS"] == {mol_class((A, A, A)): 1,
                          mol_class((A, A, T)): 2,
                          mol_class((T, A, A)): 2}

    # ---- spelled molecules cannot reach d* --------------------------------
    spelled_vecs = {tuple(spec.get(m, 0) for m in cert["molecules"])
                    for spec in cert["spelled"].values()}
    print()
    print(f"  single-molecule spectra with these reads (|D| <= {N+2}): "
          f"{len(spelled_vecs)}")
    assert cert["best"] not in spelled_vecs, \
        "expected the ML optimum to be non-spellable"
    print(f"  d* = {cert['best']} is NOT among them  ->  arbitrary flow, "
          f"not a sequence spectrum")

    # ---- bounded search ----------------------------------------------------
    print()
    print("Bounded exhaustive search")
    print("-" * 68)
    hits = bounded_search()
    seen = set()
    uniq = []
    for h in sorted(hits, key=lambda z: -z["ratio"]):
        key = (h["S"], h["starts"], h["o_min"])
        if key in seen:
            continue
        seen.add(key)
        uniq.append(h)
    print(f"  box: G in (4,5,6,7), L=3, N=G, o_min in (1,2), n in (2,3,4), "
          f"all start multisets")
    print(f"  flowing hits: {len(uniq)}")
    ns = [h for h in uniq if not h["best_spellable"]]
    print(f"  non-spellable-optimum hits (arbitrary flow strictly better "
          f"than every molecule): {len(ns)}")
    for h in uniq[:16]:
        comp = " ".join(f"{word(molecules_i)}:{v}" for molecules_i, v
                        in zip([word(m) for m in h["molecules"]], h["best"]))
        print(f"    S={word(h['S'])} starts={list(h['starts'])} "
              f"o_min={h['o_min']} d_S={h['dS']} d*={h['best']} "
              f"ratio={h['ratio']} spellable={h['best_spellable']}")
    assert all(h["ratio"] > 1 for h in uniq)

    # ---- negative boundary -------------------------------------------------
    print()
    print("Negative boundary inside the box")
    print("-" * 68)
    distinct_hits = [h for h in uniq if len(set(h["starts"])) == len(h["starts"])]
    print(f"  (i) no non-spellable-optimum hit with distinct read starts "
          f"exists in this box: "
          f"{all(h['best_spellable'] for h in distinct_hits)}")
    om2 = [h for h in uniq if h["o_min"] == 2]
    print(f"  (ii) every o_min=2 hit has a spellable optimum: "
          f"{all(h['best_spellable'] for h in om2)}")
    assert all(h["best_spellable"] for h in distinct_hits)
    assert all(h["best_spellable"] for h in om2)

    print()
    print("All assertions passed.")


if __name__ == "__main__":
    main()
