#!/usr/bin/env python3
"""Structural obstructive route for issue #36: does Shomorony bridging plus
truth feasibility force the truth copy-count flow to maximise the fixed-``N``
Medvedev--Brudno Section 6.1 binomial objective?

Object fixed here (see docs/se62-ml-cycle-obstruction.md):

* reads are DNA molecules = unordered reverse-complement pairs; on the binary
  alphabet ``A=0, T=1`` the involution is ``0 <-> 1`` and a read type is the
  class ``min(w, rc(w))``;
* the Section 6.2 read-overlap graph is bidirected with proper overlaps of
  length ``>= o_min`` and is transitively reduced as in Myers (2005); every
  read vertex has lower bound ``1``, edge lower bounds ``0``, upper bounds
  infinity, and (Observation 7) the vertex flow ``d_w`` is the number of
  occurrences of read ``w`` in the spelled molecules;
* the objective is the Section 6.1 separable product of binomial marginals
  with the external known genome length ``N``:
  ``L(d) = prod_w (d_w/N)^{x_w} (1 - d_w/N)^{n - x_w}``, ``n = sum_w x_w``.

The script verifies, with exact ``fractions.Fraction`` arithmetic:

A.  The one-variable binomial factor ``g_X(t) = (t/N)^X (1 - t/N)^{n-X}`` is
    strictly log-concave on ``0 <= t <= N``; equivalently its admissible
    increments satisfy the subadditivity inequality
        g(x+a+b) * g(x) <= g(x+a) * g(x+b),
    which is the log form of  Delta(a+b) <= Delta(a) + Delta(b).

B.  The two exact one-step signs of the marginal ratio
        rho = g_X(t+1) / g_X(t):
      * if ``n (t+1) <= N X`` then ``rho > 1`` (the clean sufficient
        condition);
      * if ``n t >= N X`` then ``rho <= 1``;
    and the two boundary examples showing the linear condition is sufficient
    but not necessary: the witness straddles the real maximiser
    (X,n,N,t) = (1,3,5,1) yet has ``rho = 9/8 > 1``, while (1,100,101,1)
    has ``t < N X / n`` yet ``rho < 1``.

C.  For the ``AAATT`` read set ``{AAA, AAT, TAA}`` (``L = 3``, ``o_min`` in
    ``{1,2}``) the reduced circulation cone is generated by the throughput
    vectors ``(1,0,0)`` (the ``AAA`` self-loop) and ``(0,1,1)`` (the
    ``AAT <-> TAA`` two-cycle).  Hence every closed Section 6.2 flow has
    ``d_AAT = d_TAA`` and the closed-flow feasible set is ``{(a,k,k)}``.

D.  At the truth ``d_S = (1,2,2)`` with ``x = (1,1,1)``, ``n = 3``, ``N = 5``
    exactly the self-loop generator ``(1,0,0)`` is profitable
    (``L(d_S + (1,0,0)) / L(d_S) = 9/8``), while the two-cycle generator
    ``(0,1,1)`` is not.  A brute-force enumeration of every closed-flow
    throughput with ``1 <= d_w <= N`` confirms ``(2,2,2)`` is the unique
    maximiser, so the truth is not optimal.

E.  Multiplicity decoupling: bridging is a property of the read *support*, not
    of the read multiplicities.  With the same support ``{AAA, AAT, TAA}`` and
    the same truth flow ``d_S = (1,2,2)``:
      * ``x = (1,1,1)`` (``n = 3``) makes the truth non-optimal (ratio 9/8);
      * ``x = (1,2,2)`` (``n = 5``) makes the truth the coordinatewise real
        maximiser, hence optimal.
    The two instances satisfy the same Section 6.2/``I_s`` structure, so no
    function of bridging alone can force optimality.

Exits non-zero on any failed assertion.  Independent of the branch packets;
it uses only exact integer/rational arithmetic and the source-faithful
bidirected port model reproduced in the Section 6.2 cone note.
"""

from collections import defaultdict
from fractions import Fraction
from itertools import product

# ---------------------------------------------------------------------------
# Section 6.1 separable binomial objective
# ---------------------------------------------------------------------------


def binom_factor(X, n, N, t):
    """The unnormalised marginal ``(t/N)^X (1 - t/N)^{n-X}`` as a Fraction.

    The ``C(n, X)`` constant does not depend on ``t`` and cancels in every
    comparison below, so it is omitted.  Returns ``None`` for ``t`` outside
    ``[0, N]``.
    """
    if t < 0 or t > N or X < 0 or X > n:
        return None
    return Fraction(t, N) ** X * (1 - Fraction(t, N)) ** (n - X)


def likelihood(x, n, N, d):
    """Product of the per-coordinate marginals (constants dropped)."""
    out = Fraction(1)
    for X, dw in zip(x, d):
        f = binom_factor(X, n, N, dw)
        if f is None:
            return None
        out *= f
    return out


def ratio_one_step(X, n, N, t):
    """Exact ratio ``g_X(t+1)/g_X(t)`` (``t+1 <= N``).

    Returns ``None`` when the denominator vanishes (``t = 0`` and ``X > 0``);
    in that case the increment is strictly positive whenever ``X > 0``.
    """
    lo = binom_factor(X, n, N, t)
    hi = binom_factor(X, n, N, t + 1)
    if lo == 0:
        return None
    return hi / lo


# ---------------------------------------------------------------------------
# A. log-concavity / subadditivity of the marginal
# ---------------------------------------------------------------------------


def check_subadditivity():
    violations = 0
    checked = 0
    for n in range(1, 8):
        for X in range(0, n + 1):
            for N in range(1, 8):
                for x in range(0, N + 1):
                    gx = binom_factor(X, n, N, x)
                    if gx is None or gx == 0:
                        continue
                    for a in range(0, N - x + 1):
                        for b in range(0, N - x - a + 1):
                            checked += 1
                            lhs = binom_factor(X, n, N, x + a + b) * gx
                            rhs = binom_factor(X, n, N, x + a) * \
                                binom_factor(X, n, N, x + b)
                            if lhs > rhs:
                                violations += 1
    assert violations == 0, violations
    return checked


# ---------------------------------------------------------------------------
# B. one-step threshold signs
# ---------------------------------------------------------------------------


def check_one_step():
    suff = neg = 0
    for n in range(1, 12):
        for N in range(1, 12):
            for X in range(0, n + 1):
                for t in range(0, N):
                    r = ratio_one_step(X, n, N, t)
                    if r is None:
                        # denominator zero: increment is positive exactly when
                        # the next factor is positive
                        if n * (t + 1) <= N * X:
                            assert binom_factor(X, n, N, t + 1) > 0
                            suff += 1
                        continue
                    if n * (t + 1) <= N * X:
                        assert r > 1, ("sufficient failed", X, n, N, t, r)
                        suff += 1
                    if n * t >= N * X:
                        assert r <= 1, ("nonprofit failed", X, n, N, t, r)
                        neg += 1
    # straddle witness: t < N X / n < t+1 yet profitable
    ws = ratio_one_step(1, 3, 5, 1)
    assert ws == Fraction(9, 8), ws
    assert Fraction(1) < Fraction(5, 3) < Fraction(2)
    # clean sufficient condition satisfied
    assert ratio_one_step(1, 2, 5, 1) == Fraction(3, 2)
    # over-target: not profitable
    assert ratio_one_step(1, 3, 5, 2) == Fraction(2, 3)
    # under-observation t < N X / n is not sufficient
    ns = ratio_one_step(1, 100, 101, 1)
    assert ns < 1, ns
    assert Fraction(1) < Fraction(101, 100)
    return suff, neg, ws, ns


# ---------------------------------------------------------------------------
# Section 6.2 bidirected port graph for the reads {AAA, AAT, TAA}
# ---------------------------------------------------------------------------

A, T = 0, 1
CANON = {"AAA": (A, A, A), "AAT": (A, A, T), "TAA": (T, A, A)}
OBS = set(CANON.values())
KEYS = ["AAA", "AAT", "TAA"]


def revcomp(w):
    return tuple(1 - b for b in reversed(w))


def mol_class(w):
    return min(w, revcomp(w))


def strand_entry(name, q):
    w = CANON[name]
    return w if q == 0 else revcomp(w)


def directed_port_edges(length):
    out = []
    for Xn in CANON:
        for Yn in CANON:
            for p in (0, 1):
                for q in (0, 1):
                    su = strand_entry(Xn, 1 - p)
                    sv = strand_entry(Yn, q)
                    if su[3 - length:] == sv[:length]:
                        out.append((Xn, p, Yn, q))
    return out


def reducible(edge, length):
    if length > 1:
        return False
    Xn, p, Yn, q = edge
    su = strand_entry(Xn, 1 - p)
    sv = strand_entry(Yn, q)
    mol = su + sv[1:]
    return mol_class(tuple(mol[1:4])) in OBS


def build_walk_graph(edges):
    adj = defaultdict(list)
    for (Xn, p, Yn, q) in edges:
        adj[(Xn, p)].append(((Yn, 1 - q), Yn))
    return adj


def elementary_circuit_vectors(adj, maxlen=12):
    """All elementary circuit throughput vectors (as 3-tuples over KEYS)."""
    states = sorted(adj)
    idx = {s: i for i, s in enumerate(states)}
    seen = set()

    def dfs(start, cur, vis, path):
        for (nxt, Yn) in adj[cur]:
            if nxt == start:
                tr = tuple((states.index(c), Yn) for (c, Yn) in path + [(cur, Yn)])
                if min(t[0] for t in tr) == idx[start]:
                    seen.add(tr)
            elif nxt not in vis and len(path) < maxlen:
                dfs(start, nxt, vis + [nxt], path + [(cur, Yn)])

    for start in states:
        dfs(start, start, [start], [])
    vecs = set()
    for tr in seen:
        c = defaultdict(int)
        for (_, Yn) in tr:
            c[Yn] += 1
        vecs.add(tuple(c.get(k, 0) for k in KEYS))
    return vecs


def monoid(gens, bound):
    reach = {(0, 0, 0)}
    changed = True
    while changed:
        changed = False
        for v in list(reach):
            for g in gens:
                w = tuple(a + b for a, b in zip(v, g))
                if sum(w) <= bound and w not in reach:
                    reach.add(w)
                    changed = True
    return reach


def check_flow_cone_and_obstruction():
    # reduced graph
    e2 = directed_port_edges(2)
    e1 = directed_port_edges(1)
    assert len(e2) == 10 and len(e1) == 18
    kept1 = [e for e in e1 if not reducible(e, 1)]
    assert set(kept1) == {("AAT", 1, "TAA", 0), ("TAA", 0, "AAT", 1)}
    adj_red = build_walk_graph(e2 + kept1)
    cyc = elementary_circuit_vectors(adj_red)
    assert all(v[1] == v[2] for v in cyc)
    assert (1, 0, 0) in cyc and (0, 1, 1) in cyc

    gens = sorted(cyc)
    reach = monoid(cyc, bound=3 * 5)  # up to 3*N

    # closed-flow feasible set with the lower bound 1 on every read vertex;
    # the Hilbert basis of the reduced circulation cone is {(1,0,0),(0,1,1)}
    assert all(v[1] == v[2] for v in reach)
    for a in range(1, 6):
        for k in range(1, 6):
            if a + 2 * k <= 15:
                assert (a, k, k) in reach, (a, k, k)
    assert (2, 2, 1) not in reach
    feasible = [d for d in reach if all(1 <= dw <= 5 for dw in d)]
    assert sorted(feasible) == sorted(
        (a, k, k) for a in range(1, 6) for k in range(1, 6)), sorted(feasible)

    # D. truthful instance, x = (1,1,1), n = 3, N = 5
    x = (1, 1, 1)
    n, N = 3, 5
    dS = (1, 2, 2)
    assert dS in feasible
    likS = likelihood(x, n, N, dS)
    enriched = [(likelihood(x, n, N, d), d) for d in feasible]
    best = max(enriched)
    assert best[1] == (2, 2, 2), best
    ratio = best[0] / likS
    assert ratio == Fraction(9, 8), ratio

    # generator profitability at dS
    prof = {}
    for g in gens:
        d2 = tuple(a + b for a, b in zip(dS, g))
        if not all(dw <= N for dw in d2):
            prof[g] = None
            continue
        prof[g] = likelihood(x, n, N, d2) / likS
    assert prof[(1, 0, 0)] == Fraction(9, 8), prof
    assert prof[(0, 1, 1)] == Fraction(4, 9), prof
    profitable = [g for g, r in prof.items() if r is not None and r > 1]
    assert profitable == [(1, 0, 0)], profitable

    # E. multiplicity decoupling: same support, different observed counts
    x2 = (1, 2, 2)
    n2, N2 = 5, 5
    assert dS in [d for d in reach if all(1 <= dw <= 5 for dw in d)]
    likS2 = likelihood(x2, n2, N2, dS)
    best2 = max((likelihood(x2, n2, N2, d), d) for d in feasible)
    # dS is the coordinatewise real maximiser, so it is the unique maximum
    assert best2[1] == dS, best2
    assert best2[0] == likS2, (best2[0], likS2)

    return {
        "generators": gens,
        "n_feasible": len(feasible),
        "best111": best,
        "ratio111": ratio,
        "ratio2cycle": prof[(0, 1, 1)],
        "best122": best2,
    }


def main():
    checked = check_subadditivity()
    suff, neg, ws, ns = check_one_step()
    flow = check_flow_cone_and_obstruction()

    print("PASS: Section 6.2 ML cycle obstruction")
    print(f"  subadditivity inequalities checked : {checked}")
    print(f"  sufficient one-step cases checked  : {suff}")
    print(f"  non-profitable cases checked       : {neg}")
    print(f"  straddle profitable ratio (1,3,5,1): {ws}")
    print(f"  under-observed but non-profit (1,100,101,1): "
          f"rho = {float(ns):.4f} < 1")
    print(f"  Hilbert basis of circulation cone  : (1,0,0), (0,1,1)"
          f"  [all circuit vectors: {len(flow['generators'])}]")
    print(f"  feasible closed flows (1<=d<=N)     : {flow['n_feasible']}")
    print(f"  ML optimum at x=(1,1,1)             : {flow['best111'][1]}"
          f"  ratio / truth = {flow['ratio111']}")
    print(f"  two-cycle generator increment       : "
          f"{flow['ratio2cycle']} (< 1)")
    print(f"  ML optimum at x=(1,2,2)             : {flow['best122'][1]}"
          f"  (truth; multiplicity decoupling)")


if __name__ == "__main__":
    main()
