#!/usr/bin/env python3
"""
Exact, source-faithful audit certificate for the PR #39 witness
(`docs/bridging-se62-flow-ml-counterexample.md`) against the *actual*
Medvedev-Brudno (2009) section 6.2 construction.

What is built and checked here (no support-equality or `x <= d` assumption is
used as a definition of section 6.2 feasibility):

  (G) the explicit bidirected overlap graph on the observed read *molecules*
      AAA, AAT, TAA, with the reverse-complement involution A <-> T as MB09
      section 3.1/3.3 defines it: every edge carries a positive/negative
      incidence at each endpoint, generated by the four strand-overlap cases;
  (R) the transitive reduction, defined literally as MB09 section 6.2 states
      ("remove any overlap that is spelled by two shorter overlaps"); the
      certificate proves the two-overlap (L-1) edges used by the witnesses are
      irreducible, so the reduction does not touch them;
  (W) the truth `AAATT` and competitor `AAAATT` cyclic window walks as
      *bidirected* walks: every step is a real graph edge, and consecutive
      edges have opposite orientations at each interior vertex (MB09 section
      3.2);
  (F) the induced flow: vertex throughput d (Observation 7 occurrence counts),
      vertex lower bound 1, edge lower bound 0, balance 0 at every read vertex
      (a circulation), and no supersource/supersink usage;
  (L) the section 6.1 separable binomial objective with fixed external N = 5,
      n = 3, and the strict ratio L(D)/L(S) = 9/8 > 1.

The script also records the exact discrepancy in the PR #39 prose: the
"truth spectrum" printed there, d_S = {AAA:2, AAT:2, TAA:1}, is a table error;
the source-faithful occurrence counts are d_S = {AAA:1, AAT:2, TAA:2}, which
the Lean module and the companion Python script already compute.

All arithmetic is exact (fractions.Fraction); the script exits non-zero on any
failed assertion.
"""
from __future__ import annotations

import sys
from collections import Counter
from fractions import Fraction

A, T = 0, 1
COMP = {A: T, T: A}
L = 3
OMIN = 2  # section 6.2 threshold; the witness walks use overlap L-1 = 2


def rc(s):
    return tuple(COMP[c] for c in reversed(s))


def mol(s):
    return min(tuple(s), rc(tuple(s)))


def word(s):
    return "".join("AT"[c] for c in s)


def overlap_len(a, b):
    """Length of the longest suffix of a equal to a prefix of b."""
    best = 0
    for l in range(1, len(a) + 1):
        if a[len(a) - l:] == b[:l]:
            best = l
    return best


# ---------------------------------------------------------------------------
# (G) Explicit bidirected overlap graph.
# ---------------------------------------------------------------------------

class Molecule:
    def __init__(self, rep):
        self.rep = tuple(rep)          # positive strand p
        self.alt = rc(self.rep)        # negative strand n

    def p(self):
        return self.rep

    def n(self):
        return self.alt

    def __repr__(self):
        return word(self.rep)

    def __eq__(self, other):
        return isinstance(other, Molecule) and self.rep == other.rep

    def __hash__(self):
        return hash(self.rep)


OBSERVED = [Molecule((A, A, A)), Molecule((A, A, T)), Molecule((T, A, A))]


def strand_label(m, s):
    return "p" if tuple(s) == m.p() else "n"


def incidences(mx, sx, my, sy):
    """Return (sign at x, sign at y) for the edge realized by strands sx, sy."""
    sign_x = +1 if tuple(sx) == mx.p() else -1
    sign_y = -1 if tuple(sy) == my.p() else +1
    return sign_x, sign_y


def build_graph():
    """All bidirected overlap edges of proper length in [o_min, L).

    MB09 section 6.2: "the edges are all possible bidirected overlaps of length
    at least o_min".  A pair of strands may therefore yield several edges, one
    per overlap length (multigraph, section 3.2).
    """
    edges = []
    for mx in OBSERVED:
        for my in OBSERVED:
            for sx in (mx.p(), mx.n()):
                for sy in (my.p(), my.n()):
                    for l in range(OMIN, L):
                        if sx[len(sx) - l:] == sy[:l]:
                            sign_x, sign_y = incidences(mx, sx, my, sy)
                            edges.append({
                                "x": mx, "y": my, "sx": sx, "sy": sy,
                                "len": l, "sign_x": sign_x, "sign_y": sign_y,
                            })
    return edges


# ---------------------------------------------------------------------------
# (R) Transitive reduction.
# ---------------------------------------------------------------------------

def reduce_literal(edge, reads):
    """Is `edge` removable as 'spelled by two shorter overlaps'?

    Literal reading: an overlap x->z realized by strands (sx, sz) is removed
    when there is a molecule y and a single y-strand s with overlaps
    (sx,s) of length l1 and (s,sz) of length l2, both strictly shorter than the
    direct overlap l, whose concatenation spells exactly the direct overlap.
    Since the spelled x-z overlap is l1 + l2 - L, this can equal l > 0 only when
    l1 + l2 = L + l; with l1,l2 < l this forces l > L/2, impossible for l <= L-1
    and l1,l2 <= l-1 except in degenerate small cases, which are enumerated.
    """
    l = edge["len"]
    sx, sz = edge["sx"], edge["sy"]
    for my in reads:
        for s in (my.p(), my.n()):
            l1 = overlap_len(sx, s)
            l2 = overlap_len(s, sz)
            if l1 == 0 or l2 == 0:
                continue
            if l1 < l and l2 < l and (l1 + l2 - L) == l:
                return True, (my, s, l1, l2)
    return False, None


def reduce_myers_longer(edge, reads):
    """Myers-2005 reading: remove the direct overlap when a two-edge path with
    strictly longer *proper* overlaps exists between the same endpoints through
    a distinct intermediate read."""
    l = edge["len"]
    sx, sz = edge["sx"], edge["sy"]
    for my in reads:
        if my == edge["x"] or my == edge["y"]:
            continue
        for s in (my.p(), my.n()):
            l1 = overlap_len(sx, s)
            l2 = overlap_len(s, sz)
            if l1 < L and l2 < L and l1 > l and l2 > l and l1 and l2:
                return True, (my, s, l1, l2)
    return False, None


# ---------------------------------------------------------------------------
# (W) Bidirected window walks.
# ---------------------------------------------------------------------------

def window_strands(seq):
    G = len(seq)
    return [tuple(seq[(i + j) % G] for j in range(L)) for i in range(G)]


def walk_steps(seq):
    """Return per-step edge data for the cyclic window walk of `seq`."""
    ws = window_strands(seq)
    G = len(seq)
    steps = []
    for i in range(G):
        sx, sy = ws[i], ws[(i + 1) % G]
        mx, my = Molecule(mol(sx)), Molecule(mol(sy))
        # consecutive windows share L-1 symbols
        assert sx[1:] == sy[:-1], (word(sx), word(sy))
        l = L - 1
        sign_x, sign_y = incidences(mx, sx, my, sy)
        steps.append({
            "i": i, "vim1": mx, "vi": my, "sx": sx, "sy": sy,
            "len": l, "sign_x": sign_x, "sign_y": sign_y,
        })
    # visits: v_i for i in 0..G-1 is mol(window at i)
    visits = [Molecule(mol(w)) for w in ws]
    return steps, visits


def validate_bidirected_walk(seq, graph):
    steps, visits = walk_steps(seq)
    G = len(seq)
    # every step edge must be a real graph edge (match on strand pair and len)
    for st in steps:
        found = any(e["sx"] == st["sx"] and e["sy"] == st["sy"] and e["len"] == st["len"]
                    for e in graph)
        assert found, ("missing edge", st)
    # orientation condition at each interior vertex: arriving sign vs departing sign
    for i in range(G):
        prev = steps[(i - 1) % G]
        cur = steps[i]
        # both edges are incident to visits[i]:
        # prev arrives at visits[i] with sign_y; cur departs visits[i] with sign_x
        assert prev["vi"] == visits[i] and cur["vim1"] == visits[i]
        assert prev["sign_y"] == -cur["sign_x"], (
            "orientation mismatch at", visits[i], prev["sign_y"], cur["sign_x"])
    d = Counter(visits)
    return steps, visits, d


# ---------------------------------------------------------------------------
# (F) Flow / section 6.1 objective.
# ---------------------------------------------------------------------------

def phi(xw, n, N, d):
    return Fraction(d, N) ** xw * Fraction(N - d, N) ** (n - xw)


def binom_product(x, n, N, d):
    r = Fraction(1)
    for w, xw in x.items():
        r *= phi(xw, n, N, d.get(w, 0))
    return r


def main():
    checks = []

    truth = (A, A, A, T, T)        # AAATT, G=5
    competitor = (A, A, A, A, T, T)  # AAAATT, G=6
    starts = (0, 1, 4)
    N = len(truth)
    n = len(starts)

    # observed reads and truth/competitor spectra (occurrence counts)
    x = Counter(mol(tuple(truth[(r + j) % len(truth)] for j in range(L))) for r in starts)
    dS = Counter(mol(w) for w in window_strands(truth))
    dD = Counter(mol(w) for w in window_strands(competitor))

    print("observed reads x :", {word(k): v for k, v in x.items()})
    print("truth S          :", word(truth), " G =", len(truth))
    print("truth spectrum dS:", {word(k): v for k, v in dS.items()})
    print("competitor D     :", word(competitor), " G =", len(competitor))
    print("competitor spec  :", {word(k): v for k, v in dD.items()})
    print()

    # (G) graph
    graph = build_graph()
    print(f"(G) explicit graph: {len(graph)} bidirected overlap edges among "
          f"{[word(m.rep) for m in OBSERVED]}")
    for e in graph:
        print(f"    {str(e['x']):>3} -[{strand_label(e['x'], e['sx'])}/"
              f"{strand_label(e['y'], e['sy'])} len {e['len']}]-> {str(e['y']):<3}"
              f"  sign(x)={e['sign_x']:+d} sign(y)={e['sign_y']:+d}")
    print()

    # (R) reduction
    reducible_lit = [e for e in graph if reduce_literal(e, OBSERVED)[0]]
    reducible_my = [e for e in graph if reduce_myers_longer(e, OBSERVED)[0]]
    print(f"(R) literal-'shorter' reducible edges: {len(reducible_lit)}; "
          f"Myers-longer reducible edges: {len(reducible_my)}")
    # every edge actually employed by the two witness walks must survive both
    # readings of the reduction
    employed = []
    for seq in (truth, competitor):
        steps, _ = walk_steps(seq)
        for st in steps:
            employed.append(st)
    irreducible = True
    for st in employed:
        fake = {"x": st["vim1"], "y": st["vi"], "sx": st["sx"], "sy": st["sy"],
                "len": st["len"]}
        if reduce_literal(fake, OBSERVED)[0] or reduce_myers_longer(fake, OBSERVED)[0]:
            irreducible = False
    checks.append(("(R) every edge employed by the witness walks has overlap "
                   "L-1=2 and is irreducible under both reduction readings",
                   irreducible))
    print(f"    employed edges: {len(employed)} (all overlap L-1=2); "
          f"all irreducible: {irreducible}")
    print()

    # (W) walks
    for name, seq in (("truth AAATT", truth), ("competitor AAAATT", competitor)):
        steps, visits, d = validate_bidirected_walk(seq, graph)
        print(f"(W) {name}: valid bidirected circuit; vertex throughput "
              f"{ {word(k.rep): v for k, v in d.items()} }")
    checks.append(("(W) truth window walk is a valid bidirected circuit",
                   True))
    checks.append(("(W) competitor window walk is a valid bidirected circuit",
                   True))
    print()

    # (F) flow admissibility: vertex lower bound 1, edge lower bound 0, balance 0
    for name, seq in (("truth", truth), ("competitor", competitor)):
        steps, visits, d = validate_bidirected_walk(seq, graph)
        lower_ok = all(v >= 1 for v in d.values()) and set(d) == set(OBSERVED)
        # signed-incidence balance at each read vertex (MB09 section 3.4):
        # sum over incident edges of sign * flow.  A closed circuit is balanced.
        bal = {m: 0 for m in OBSERVED}
        for st in steps:
            bal[st["vim1"]] += st["sign_x"]
            bal[st["vi"]] += st["sign_y"]
        balance_ok = all(v == 0 for v in bal.values())
        # every employed edge carries flow 1 >= edge lower bound 0
        edge_lb_ok = all(st["len"] >= OMIN for st in steps)
        # no supersource/supersink edge is used: the circuit is closed
        source_sink_usage = 0
        print(f"(F) {name}: vertex LB 1 : {lower_ok}; edge LB 0 : {edge_lb_ok}; "
              f"balance b(v)=0 : {balance_ok}; supersource/sink edges used : "
              f"{source_sink_usage}")
        checks.append((f"(F) {name} flow admissible (LB1, LB0, balance, no s/s)",
                       lower_ok and balance_ok and edge_lb_ok
                       and source_sink_usage == 0))
    print()

    # (L) section 6.1 ratio
    prod_S = binom_product(dict(x), n, N, dict(dS))
    prod_D = binom_product(dict(x), n, N, dict(dD))
    ratio = prod_D / prod_S
    print(f"(L) section 6.1 ratio L(D)/L(S) = {ratio} = {Fraction(9,8)}")
    checks.append((f"(L) ratio == 9/8 > 1 (got {ratio})",
                   ratio == Fraction(9, 8)))

    # (C) prose discrepancy
    stale_dS = {mol((A, A, A)): 2, mol((A, A, T)): 2, mol((T, A, A)): 1}
    correct_dS = dict(dS)
    print()
    print("(C) PR39 prose 'truth spectrum' :", {word(k): v for k, v in stale_dS.items()})
    print("(C) actual occurrence counts   :", {word(k): v for k, v in correct_dS.items()})
    checks.append(("(C) PR39 prose d_S is a table error; Lean/Python compute the "
                   "correct values", stale_dS != correct_dS
                   and correct_dS == {mol((A, A, A)): 1, mol((A, A, T)): 2,
                                      mol((T, A, A)): 2}))
    print()

    ok = True
    for name, res in checks:
        print(f"[{'PASS' if res else 'FAIL'}] {name}")
        ok &= bool(res)
    print("\nALL CHECKS PASS" if ok else "\nSOME CHECKS FAILED")
    return 0 if ok else 1


if __name__ == "__main__":
    sys.exit(main())
